### ISSUE TITLE
Read below

### ISSUE THREAD

**Issue by Codepulze** [bestadamdagoat/WebSocket-Sniper#1]
Hello reading through your code i saw like Valyse exectuor, can you provide me some proof that Valyse is a Malware? Or any proof?

**Comment by bestadamdagoat** [comment]
yeah i might just remove that part altogether because i get my reports from 3rd parties.

**Comment by bestadamdagoat** [comment]
apparently the owner has a history of hiding malware with his programs. it’s also not trusted within the community.

**Comment by Codepulze** [comment]
alr
